name: Capture new charts

on:
  push:
    branches:
      - master
    paths:
      - 'data/**.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn

      - name: Capture and extract all charts images
        run: |
          cd webshooter
          node captureAllCharts.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          base: master
          branch: charts-captures
          commit-message: 'feat(captures): update charts captures'
          committer: Javier López <javierlopez@uc.cl>
          title: Update Charts Captures
          body: Data was updated, therefore, we update all charts captures.
          author: Javier López <javierlopez@uc.cl>
